
var words =
["Alternative Investment Fund Managers Directive 2011",
"ATEX directive",
"Battery Directive",
"Best available technology",
"Biocidal Products Directive",
"Birds Directive",
"Capital Adequacy Directive",
"Capital Requirements Directives",
"CHP Directive",
"Citizens’ Rights Directive",
"Clinical Trials Directive",
"Collective Redundancies Directive 1998",
"Commission Directive 91/71/EEC",
"Computer Programs Directive",
"Conditional Access Directive",
"Construction Products Directive",
"Consumer Rights Directive 2011",
"Copyright Directive",
"Copyright Duration Directive",
"Copyright Term Directive",
"Cosmetics Directive",
"Council Regulation (EC) No 1/2005",
"Dangerous Preparations Directive",
"Dangerous Substances Directive (67/548/EEC)",
"Data Protection Directive",
"Data Retention Directive",
"Database Directive",
"Directive on Copyright in the Digital Single Market",
"Directive on the energy performance of buildings",
"Directive on the legal protection of biotechnological inventions",
"Directive on the legal protection of designs",
"Directive on the re-use of public sector information",
"Drinking Water Directive 1998",
"Electronic Commerce Directive 2000",
"Electronic Signatures Directive",
"Employee Involvement Directive 2001",
"Employment discrimination law in the European Union",
"End of Life Vehicles Directive",
"Enforcement Directive",
"Environmental Liability Directive 2004",
"Environmental Noise Directive",
"EPrivacy Regulation",
"Equality Framework Directive 2000",
"EU Directive 2010/63/EU",
"EU Directive on Electricity Production from Renewable Energy Sources 2001/77/EC",
"EU Energy Efficiency Directive 2012",
"EU FLEGT Action Plan",
"EU medical device regulation",
"EU Tissue Directive",
"European Cocoa and Chocolate Directive",
"European Directive on Traditional Herbal Medicinal Products",
"European Firearms Directive",
"European hazard symbols",
"European Investigation Order",
"European SEA Directive 2001/42/EC",
"European Union Council Directive 1999/74/EC",
"European units of measurement directives",
"European Works Council Directive 2009",
"Falsified Medicines Directive",
"Floods Directive",
"Framework Directive",
"Freedom of access to information Directive",
"Good Clinical Practice Directive",
"Good Environmental Status",
"Habitats Directive",
"Industrial Emissions Directive",
"Infrastructure for Spatial Information in the European Community",
"Institutions for Occupational Retirement Provision Directive 2003",
"Integrated Pollution Prevention and Control",
"Internal Market in Electricity Directive",
"International Material Data System",
"Landfill Directive",
"Large Combustion Plant Directive",
"Late Payment Directive",
"List of European Union directives",
"Low Voltage Directive",
"Machinery Directive",
"Marine Equipment Directive 96/98/EC",
"Marine Strategy Framework Directive",
"Markets in Financial Instruments Directive 2004",
"Measuring Instruments Directive",
"Medical Devices Directive",
"Mortgage Credit Directive",
"National Renewable Energy Action Plan",
"Nickel Directive",
"Packaging and packaging waste directive",
"Parental Leave Directive 2010",
"Posted Workers Directive 1996",
"Pressure Equipment Directive",
"Privacy and Electronic Communications Directive 2002",
"Race Equality Directive 2000",
"Radio Equipment Directive",
"Recreational Craft Directive",
"Renewable Energy Directive 2009",
"Rental Directive",
"Resale Rights Directive",
"Restriction of Hazardous Substances Directive",
"Satellite and Cable Directive",
"Savings Directive",
"Services in the Internal Market Directive 2006",
"Shareholder Rights Directive 2007",
"Sui generis database right",
"Temporary Agency Work Directive 2008",
"Tobacco Products Directive",
"Trade Marks Directive",
"Transport Biofuels Directive 2003",
"Undertakings for Collective Investment in Transferable Securities Directive 2009",
"Unfair Commercial Practices Directive 2005",
"Unfair Terms in Consumer Contracts Directive 1993",
"Universal Service Directive 2002",
"Urban Waste Water Treatment Directive",
"Waste Electrical and Electronic Equipment Directive",
"Waste framework directive",
"Waste Incineration Directive",
"Water Framework Directive",
"Working Time Directive 2003"
];

window.addEventListener("load", function() {
		var randoms = window.document.getElementsByClassName("randoms");
		for (i = 0; i < randoms.length; i++)
				changeWord(randoms[i]);
}, false);

function changeWord(a) {
		a.style.opacity = '0.1';
		a.innerHTML = words[getRandomInt(0, words.length - 1)];
		setTimeout(function() {
				a.style.opacity = '1';
		}, 425);
		setTimeout(function() {
				changeWord(a);
		}, getRandomInt(500, 800));
}


function getRandomInt(min, max) {
		return Math.floor(Math.random() * (max - min + 1)) + min;
}